/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project5;

/**
 *
 * @author Chaot
 */
public class Registration extends javax.swing.JFrame {
    
    public String username;
    public String fullName;
    public String password;
    public String email;

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        
        username = userName.getText();
        fullName = userFullName.getText();
        password = userPassword.getText();
        email = userEmail.getText();
    }
    
    public String getUsername() {
        return username;
    }
    
    public String getFullName() {
        return fullName;
    }
    
    public String getPassword() {
        return password;
    }
    
    public String getEmail() {
        return email;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mintPanel = new javax.swing.JPanel();
        registrationText = new javax.swing.JTextField();
        pinkPanel = new javax.swing.JPanel();
        userInputs = new javax.swing.JTextArea();
        userPasswordConfirm = new javax.swing.JPasswordField();
        userPassword = new javax.swing.JPasswordField();
        userFullName = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        userEmail = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mintPanel.setBackground(new java.awt.Color(180, 248, 200));

        registrationText.setEditable(false);
        registrationText.setBackground(new java.awt.Color(180, 248, 200));
        registrationText.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        registrationText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        registrationText.setText("Registration");
        registrationText.setBorder(null);

        javax.swing.GroupLayout mintPanelLayout = new javax.swing.GroupLayout(mintPanel);
        mintPanel.setLayout(mintPanelLayout);
        mintPanelLayout.setHorizontalGroup(
            mintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mintPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(registrationText, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        mintPanelLayout.setVerticalGroup(
            mintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mintPanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(registrationText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pinkPanel.setBackground(new java.awt.Color(255, 174, 188));
        pinkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userInputs.setEditable(false);
        userInputs.setBackground(new java.awt.Color(255, 174, 188));
        userInputs.setColumns(20);
        userInputs.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 18)); // NOI18N
        userInputs.setRows(5);
        userInputs.setText("Full Name:\n\n\n\nUsername:\n\n\n\nPassword:\n\n\n\nConfirm Password:\n\n\n\nEmail:");
        userInputs.setBorder(null);
        pinkPanel.add(userInputs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 134, -1));

        userPasswordConfirm.setBackground(new java.awt.Color(255, 174, 188));
        userPasswordConfirm.setText("jPasswordField1");
        userPasswordConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userPasswordConfirmFocusGained(evt);
            }
        });
        pinkPanel.add(userPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 199, -1));

        userPassword.setBackground(new java.awt.Color(255, 174, 188));
        userPassword.setText("jPasswordField2");
        userPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userPasswordFocusGained(evt);
            }
        });
        pinkPanel.add(userPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 199, -1));

        userFullName.setBackground(new java.awt.Color(255, 174, 188));
        userFullName.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 14)); // NOI18N
        userFullName.setText("Full Name");
        userFullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFullNameFocusGained(evt);
            }
        });
        pinkPanel.add(userFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 199, -1));

        userName.setBackground(new java.awt.Color(255, 174, 188));
        userName.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 14)); // NOI18N
        userName.setText("Username");
        userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFocusGained(evt);
            }
        });
        pinkPanel.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 199, -1));

        userEmail.setBackground(new java.awt.Color(255, 174, 188));
        userEmail.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 12)); // NOI18N
        userEmail.setText("Email");
        userEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userEmailFocusGained(evt);
            }
        });
        pinkPanel.add(userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 200, -1));

        exitButton.setBackground(new java.awt.Color(255, 174, 188));
        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitButton.setText("X");
        exitButton.setBorder(null);
        exitButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                exitButtonFocusGained(evt);
            }
        });
        pinkPanel.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 40, 40));

        signUpButton.setBackground(new java.awt.Color(255, 174, 188));
        signUpButton.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 12)); // NOI18N
        signUpButton.setText("Sign Up!");
        signUpButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 164, 188), 1, true));
        pinkPanel.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mintPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pinkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mintPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pinkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userFullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFullNameFocusGained
        userFullName.setText("");
    }//GEN-LAST:event_userFullNameFocusGained

    private void userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusGained
        userName.setText("");
    }//GEN-LAST:event_userNameFocusGained

    private void userPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPasswordFocusGained
        userPassword.setText("");
    }//GEN-LAST:event_userPasswordFocusGained

    private void userPasswordConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPasswordConfirmFocusGained
        userPasswordConfirm.setText("");
    }//GEN-LAST:event_userPasswordConfirmFocusGained

    private void userEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userEmailFocusGained
        userEmail.setText("");
    }//GEN-LAST:event_userEmailFocusGained

    private void exitButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_exitButtonFocusGained
        dispose();
    }//GEN-LAST:event_exitButtonFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel mintPanel;
    private javax.swing.JPanel pinkPanel;
    private javax.swing.JTextField registrationText;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField userEmail;
    private javax.swing.JTextField userFullName;
    private javax.swing.JTextArea userInputs;
    private javax.swing.JTextField userName;
    private javax.swing.JPasswordField userPassword;
    private javax.swing.JPasswordField userPasswordConfirm;
    // End of variables declaration//GEN-END:variables
}
